[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.0",
    "notion-client>=2.4.0",
    "openai>=1.93.0",
    "pinecone>=7.3.0",
    "pinecone-client>=6.0.0",
    "slack-sdk>=3.35.0",
]
